
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: studycenter_api_development

test:
  <<: *default
  database: studycenter_api_test

production:
  <<: *default
  database: studycenter_api_production
  username: studycenter_api
  password: <%= ENV['STUDYCENTER_API_DATABASE_PASSWORD'] %>
